---
name: "Quality Check(super-linter)"

on:
  push:
  workflow_call:

jobs:
  linter:
    name: "Quality Check(superlinter)"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Run Super-Linter"
        uses: super-linter/super-linter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
