---
name: cd-tag-latest
# Tags the dev image to latest and __IMAGE_VERSION__

on:
  workflow_call:
    inputs:
      registry_name:
        description: "Registry to publish images"
        type: string
        required: false
        default: "docker.io"
    secrets:
      REGISTRY_USERNAME:
        required: true
      REGISTRY_TOKEN:
        required: true

jobs:
  cd:
    name: "Retag Image(dev->latest)"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Registry Login(${{ inputs.registry_name }})
        run: |
          echo "${{ secrets.REGISTRY_TOKEN }}" | /usr/bin/podman login \
            --username "${{ secrets.REGISTRY_USERNAME }}" \
            --password-stdin ${{ inputs.registry_name }}

      - name: Pull the (dev)Image
        run: |
          set -x
          /usr/bin/podman rmi --all --force
          CONTAINER="${{ inputs.registry_name }}"
          CONTAINER+="/${{ secrets.REGISTRY_USERNAME }}"
          CONTAINER+="/$(pwd | awk -F'/' '{print $NF}')"
          MANIFEST="${CONTAINER}:build"
          /usr/bin/podman pull "${MANIFEST}-amd64"
          /usr/bin/podman pull "${MANIFEST}-arm64"
          LATEST="${CONTAINER}:latest"
          /usr/bin/podman manifest create "${LATEST}" \
                   "${MANIFEST}-amd64" "${MANIFEST}-arm64"

      - name: Tag the latest Image
        if: github.event_name == 'pull_request' && github.base_ref == 'main'
        run: |
          set -x
          CONTAINER="${{ inputs.registry_name }}"
          CONTAINER+="/${{ secrets.REGISTRY_USERNAME }}"
          CONTAINER+="/$(pwd | awk -F'/' '{print $NF}')"
          /usr/bin/podman manifest push "${CONTAINER}:latest"
          VERSION="${CONTAINER}:$(grep '^IMAGE_VERSION=' .args | cut -d= -f2-)"
          /usr/bin/podman tag "${CONTAINER}:latest" "${VERSION}"
          /usr/bin/podman manifest push "${VERSION}"
