---
name: ci-docker-clean
# This action is ment to clean up all the old docker tags base on build #

on:
  workflow_call:
    inputs:
      registry_name:
        description: "Registry to publish images"
        type: string
        required: false
        default: "docker.io"
    secrets:
      REGISTRY_USERNAME:
        required: true
      REGISTRY_TOKEN:
        required: true

jobs:
  ci:
    name: "Fetch"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jq skope

      - name: Fetch
        # yamllint disable rule:line-length
        run: |
          FOO="$(curl -fsSL https://hub.docker.com/v2/repositories/gautada/alpine/tags?page_size=100)"
          echo "${FOO}"
          which curl
          # set -Eeuo pipefail
          # REG="docker.io"
          # IMAGE="gautada/alpine"
          # curl -fsSL "https://${REG}/v2/${IMAGE}/tags/list"
          # Get tags into an array (ShellCheck-friendly, avoids word-splitting)
          # mapfile -t tags < <(
          #  curl -fsSL "https://${REG}/v2/${IMAGE}/tags/list" | jq -r '.tags[]'
          # )
          # printf 'Found %d tags\n' "${#tags[@]}"
        # yamllint enable rule:line-length
