---
name: ci-podman-arch

on:
  workflow_call:
    inputs:
      architecture:
        description: "CPU Architecture for Build"
        type: string
        required: true
      args_file:
        description: "Path to build-arg file"
        type: string
        required: false
        default: ".args"
      containerfile:
        description: "Path to Containerfile"
        type: string
        required: false
        default: "Containerfile"
      registry_name:
        description: "Registry to publish images"
        type: string
        required: false
        default: "docker.io" 
    secrets:
      REGISTRY_USERNAME:
        required: true
      REGISTRY_TOKEN:
        required: true

jobs:
  integrate:
    name: "Build & Publish Image(${{ inputs.architecture }}" 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Export .args to GITHUB_ENV (if present)
        if: ${{ hashFiles(inputs.args_file) != '' }}
        run: |
          while IFS='=' read -r key value; do
            echo "$key=$value" >> "$GITHUB_ENV"
          done < "${{ inputs.args_file }}"
      
      - name: Install Podman + QEMU
        run: |
          sudo apt-get update
          sudo apt-get install --yes qemu-user-static binfmt-support podman
          if [ "${{ inputs.architecture }}" = "arm64" ]; then
            sudo update-binfmts --enable qemu-aarch64 || true
          fi
      
      - name: Docker Hub login
        run: |
          echo "${{ secrets.REGISTRY_TOKEN }}" | podman login \
            --username "${{ secrets.REGISTRY_USERNAME }}" \
            --password-stdin ${{ inputs.registry_name }}
      
      - name: Build and Publish Image
        run: |
          TAG="${{ inputs.registry_name }}/${{ secrets.REGISTRY_USERNAME }}/"
          TAG="${TAG}${IMAGE_NAME}:build-${{ inputs.architecture }}"
          # ARCH_IN=
          # case "$ARCH_IN" in
          #   amd64) PODMAN_ARCH="amd64" ;;
          #   arm64|aarch64) PODMAN_ARCH="arm64" ;;
          #   *) echo "Unsupported architecture: $ARCH_IN" >&2; exit 1 ;;
          # esac
          podman build \
            --arch "${{ inputs.architecture }}" \
            --build-arg-file ${{ inputs.args_file }} \
            --file ${{ inputs.containerfile }} \
            --no-cache \
            --tag "${TAG}" .
          podman push "${TAG}"
          which podman
