---
name: ci-podman-dev
# Pulls together the manifest and pushes the dev tagged image to registry

on:
  workflow_call:
    inputs:
      architectures:
        description: "List of architectures"
        type: string
        required: true
      tag_dev:
        description: "Tag for development container"
        type: string
        required: false
        default: "dev"
      tag_build:
        description: "Tag for build containers"
        type: string
        required: false
        default: "build"
      registry_name:
        description: "Registry to publish images"
        type: string
        required: false
        default: "docker.io"
    secrets:
      REGISTRY_USERNAME:
        required: true
      REGISTRY_TOKEN:
        required: true

jobs:
  ci:
    name: "Integrate Development"
    runs-on: ubuntu-latest
    steps:
      - name: Registry Login
        run: |
          echo "${{ secrets.REGISTRY_TOKEN }}" | /usr/bin/podman login \
            --username "${{ secrets.REGISTRY_USERNAME }}" \
            --password-stdin ${{ inputs.registry_name }}

      - name: Publish Container
        # yamllint disable rule:line-length
        run: |
          set -x
          VERSION="$(/usr/bin/git rev-parse --short HEAD)"
          CONTAINER="${{ inputs.registry_name }}"
          CONTAINER+="/${{ secrets.REGISTRY_USERNAME }}/"
          CONTAINER+="$(pwd | awk -F'/' '{print $NF}')"
          MANIFEST="${CONTAINER}:${{ inputs.tag_dev }}}"
          /usr/bin/podman manifest create "${MANIFEST}"
          for architecture in $(echo '${{ inputs.architectures }}' | jq -r '.[]'); do
           BUILD="${CONTAINER}:${{ inputs.tag_build }}-${architecture}"
           PART="${CONTAINER}:${{ inputs.tag_build }}"
           PART+="-${architecture}"
           PART+="${VERSION}"
           /usr/bin/podman pull "${BUILD}"
           /usr/bin/podman tag "${BUILD}" "${PART}"
           /usr/bin/podman push "${PART}"
           /usr/bin/podman manifest add "${MANIFEST}" "${PART}"
          done # <<< "${{ inputs.architectures }}"
          /usr/bin/podman manifest push "${MANIFEST}"
        # yamllint enable rule:line-length
